-- ADR 0012: the prior geocoder (BrasilAPI open-cep) cached município
-- centroids, so every CEP in the store's city resolved to the same point.
-- Wipe them so every CEP re-resolves against AwesomeAPI, and make AwesomeAPI
-- the recorded default provider. cep_geocodes is a derived cache with no FK
-- dependents and the feature has not launched.
--
-- Hand-written (not generated by `prisma migrate dev`, which refuses to run
-- against this database — the Better Auth tables sit outside Prisma's migration
-- history, so Prisma reports drift; see TASK.md). Applied with
-- `prisma migrate deploy`, which runs cleanly against a DB whose history is
-- otherwise in sync.

DELETE FROM "cep_geocodes";
ALTER TABLE "cep_geocodes" ALTER COLUMN "provider" SET DEFAULT 'awesomeapi';
