import { Order } from '@/domain/quintalpet/enterprise/entities/order'

export function presentOrder(order: Order) {
	return {
		id: order.id.toString(),
		orderCode: order.orderCode,
		status: order.status,
		storeCustomerId: order.storeCustomerId?.toString() ?? null,
		guestName: order.guestName,
		guestPhone: order.guestPhone,
		items: order.items.map((item) => ({
			id: item.id.toString(),
			productId: item.productId.toString(),
			variantId: item.variantId.toString(),
			productName: item.productName,
			variantLabel: item.variantLabel,
			sku: item.sku,
			unitPriceCents: item.unitPriceCents,
			quantity: item.quantity,
			lineTotalCents: item.lineTotalCents,
			baseUnitPriceCents: item.baseUnitPriceCents,
			unitDiscountCents: item.unitDiscountCents,
			baseLineTotalCents: item.baseLineTotalCents,
			lineDiscountCents: item.lineDiscountCents,
		})),
		subtotalCents: order.subtotalCents,
		shippingCents: order.shippingCents,
		totalCents: order.totalCents,
		baseSubtotalCents: order.baseSubtotalCents,
		itemDiscountTotalCents: order.itemDiscountTotalCents,
		shippingBaseCents: order.shippingBaseCents,
		shippingDiscountCents: order.shippingDiscountCents,
		totalDiscountCents: order.totalDiscountCents,
		appliedPromotions: order.appliedPromotions,
		shippingAddress: order.shippingAddress,
		deliveryLabel: order.deliveryLabel,
		paymentMethod: order.paymentMethod,
		cancelledAt: order.cancelledAt?.toISOString() ?? null,
		createdAt: order.createdAt.toISOString(),
	}
}
